// <auto-generated />
namespace SolarMag.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init_encore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_encore));
        
        string IMigrationMetadata.Id
        {
            get { return "201804232000295_Init_encore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
